name: last-fm
on: push
jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: Get code 
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 
      - name: Install dependencies
        run: npm ci
      - name: Run build 
        run: npm run build 
  deploy:
    runs-on: macos-latest
    steps:
      - name: Get code 
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 
      - name: Install dependencies
        run: npm ci
      - name: Run build 
        run: npm run build 
      - name: Run deploy 
        run: echo "Deploying ..."